"""Initial migration

Revision ID: 2fd97aedd8ab
Revises: f5cecd453d34
Create Date: 2025-05-22 16:47:30.226355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd97aedd8ab'
down_revision: Union[str, None] = 'f5cecd453d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('games_count', sa.Integer(), nullable=False))
    op.drop_column('players', 'games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('players', 'games_count')
    # ### end Alembic commands ###
